version: '3.8'

services:
  rss-tracker_v0_feeds:
    image: flashk/rss-tracker_v0_feeds:latest
    container_name: rss-tracker_v0_feeds
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=${MONGODB_USERNAME:-admin}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-admin}
      - OAUTH2_ISSUER_URI=${OAUTH2_ISSUER_URI:-https://your-oauth-issuer-uri}
    networks:
      - rss-app-network
      
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-admin}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-rss_tracker_db}
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - rss-app-network

networks:
  rss-app-network:
    driver: bridge