server:
  port: 8080
  forward-headers-strategy: FRAMEWORK # Gateway HATEOAS urls to point to gateway

spring:
  application:
    name: rss-tracker_api_v0_feeds # Convention: [application]_api_[vN]_[resource]_[subresource]
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:rss_tracker_db}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin}
      
  # OAuth configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://your-oauth-issuer-uri}